FROM node:20-alpine

WORKDIR /app

ARG DATABASE_URL

ENV DATABASE_URL=$DATABASE_URL

COPY ./packages ./packages

COPY ./package.json ./package.json

COPY ./pnpm-lock.yaml ./pnpm-lock.yaml

COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml

COPY ./turbo.json ./turbo.json

COPY ./apps/web ./apps/web

RUN npm install -g pnpm

RUN pnpm install

RUN pnpm run db:generate

RUN pnpm run build

EXPOSE 3000

CMD ["pnpm", "run", "start:frontend"]
