FROM node:20-alpine

WORKDIR /app

COPY ./packages ./packages

COPY ./package.json ./package.json

COPY ./pnpm-lock.yaml ./pnpm-lock.yaml

COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml

COPY ./turbo.json ./turbo.json

COPY ./apps/http-backend ./apps/http-backend

RUN npm install -g pnpm

RUN pnpm install

RUN pnpm run db:generate

RUN pnpm run build

EXPOSE 8000

CMD ["pnpm", "run", "start:http-backend"]
